version: "3.9"
services:
  solr:
    image: zetregistry.azurecr.io/solr-dev:v1.0
    ports:
      - "8983:8983"
  zetaris-db:
    command: [ "postgres", "-c", "log_statement=all" ]
    image: postgres:15.1
    hostname: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./datadir/pg:/var/lib/postgresql/data/pgdata
      - ./lightning/db/postgres/initdb:/docker-entrypoint-initdb.d/
      - ./lightning/db/postgres/scripts:/scripts
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata


